version: '3'
services:
  ddns:
    container_name: ddns
    hostname: ddns
    image: jimeagle/ddns:latest
    restart: "unless-stopped"
    environment:
      - DO_KEY=xxx
      - CF_KEY=xxx
      - ONE_TIME=false
      - ON_LOAD=true
    volumes:
      - ./records.yaml:/root/records.yaml:ro
